<application>
  <component name="ActionsCollector">
    <counts>
      <entry action="$Copy" count="71" />
      <entry action="$Cut" count="7" />
      <entry action="$Delete" count="150" />
      <entry action="$Paste" count="154" />
      <entry action="$SelectAll" count="109" />
      <entry action="$Undo" count="12668" />
      <entry action="About" count="1" />
      <entry action="Android.AnalyzeApk" count="1" />
      <entry action="Android.BuildApk" count="35" />
      <entry action="Android.CreateResourceDirectory" count="3" />
      <entry action="Android.CreateSampleDataDirectory" count="2" />
      <entry action="Android.GenerateSignedApk" count="3" />
      <entry action="Android.RunAndroidAvdManager" count="24" />
      <entry action="Android.RunAndroidSdkManager" count="16" />
      <entry action="Android.SyncProject" count="10" />
      <entry action="AndroidConnectDebuggerAction" count="1" />
      <entry action="AttachDebuggerAction" count="1" />
      <entry action="AutoShowProcessWindow" count="2" />
      <entry action="ChangeFileEncodingAction" count="2" />
      <entry action="ChooseDebugConfiguration" count="1" />
      <entry action="ChooseRunConfiguration" count="5" />
      <entry action="CleanGradleProject" count="54" />
      <entry action="CloseAllEditors" count="217" />
      <entry action="CloseAllEditorsButActive" count="15" />
      <entry action="CloseAllUnpinnedEditors" count="2" />
      <entry action="CloseContent" count="3" />
      <entry action="CodeCompletion" count="1335" />
      <entry action="CollapseSelection" count="1" />
      <entry action="CollapseTreeNode" count="1" />
      <entry action="CommentByBlockComment" count="239" />
      <entry action="CommentByLineComment" count="6" />
      <entry action="CompileDirty" count="2" />
      <entry action="ConsoleView.FoldLinesLikeThis" count="1" />
      <entry action="ContextHelp" count="1" />
      <entry action="CopyAsPlainText" count="1" />
      <entry action="CopyElement" count="1" />
      <entry action="CopyPaths" count="1" />
      <entry action="CopyUrl" count="2" />
      <entry action="Dart.NewDartFile" count="14" />
      <entry action="Debug" count="40" />
      <entry action="DialogCancelAction Escape" count="